<a href="https://colab.research.google.com/github/hossainsiam133/Machine-Learning/blob/main/NumPy/01_NumPy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# NumPy Creating Arrays
import numpy as np

# From list
arr1 = np.array([1, 2, 3])
print("1D array:", arr1)

# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print("2D array:\n", arr2)

# Zeros, Ones, and Random
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Random:\n", np.random.rand(2, 3))

1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.98124326 0.50166956 0.11863674]
 [0.3800445  0.88819851 0.22637075]]


In [5]:
# NumPy Array Indexing
arr = np.array([10, 20, 30, 40])
print("Element at index 1:", arr[1])

arr2d = np.array([[1, 2], [3, 4]])
print("Element at (1, 0):", arr2d[1, 0])


Element at index 1: 20
Element at (1, 0): 3


In [6]:
# NumPy Array Slicing
arr = np.array([10, 20, 30, 40, 50])
print("Sliced (1:4):", arr[1:4])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Row 1, Col 0:2\n", arr2d[1, 0:2])

Sliced (1:4): [20 30 40]
Row 1, Col 0:2
 [4 5]


In [7]:
# NumPy Data Types
arr = np.array([1, 2, 3], dtype='float32')
print("Array:", arr)
print("Data Type:", arr.dtype)

Array: [1. 2. 3.]
Data Type: float32


In [8]:
# NumPy Copy vs View
# View (shared data)
arr = np.array([1, 2, 3])
view = arr.view()
view[0] = 100
print("Original (after view change):", arr)

# Copy (separate data)
copy = arr.copy()
copy[1] = 200
print("Original (after copy change):", arr)

Original (after view change): [100   2   3]
Original (after copy change): [100   2   3]


In [9]:
# NumPy Array Shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Size: 6
Dimensions: 2


In [10]:
# NumPy Array Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [11]:
# NumPy Array Iterating
arr = np.array([[1, 2], [3, 4]])

# Iterate over rows
for row in arr:
    print("Row:", row)

# Iterate over each element
for x in np.nditer(arr):
    print("Element:", x)

Row: [1 2]
Row: [3 4]
Element: 1
Element: 2
Element: 3
Element: 4
