<a href="https://colab.research.google.com/github/hossainsiam133/Machine-Learning/blob/main/NumPy/01_NumPy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy Creating Arrays
import numpy as np

# From list
arr1 = np.array([1, 2, 3])
print("1D array:", arr1)

# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print("2D array:\n", arr2)

# Zeros, Ones, and Random
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Random:\n", np.random.rand(2, 3))

1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.98124326 0.50166956 0.11863674]
 [0.3800445  0.88819851 0.22637075]]


In [ ]:
# NumPy Array Indexing
arr = np.array([10, 20, 30, 40])
print("Element at index 1:", arr[1])

arr2d = np.array([[1, 2], [3, 4]])
print("Element at (1, 0):", arr2d[1, 0])


Element at index 1: 20
Element at (1, 0): 3


In [ ]:
# NumPy Array Slicing
arr = np.array([10, 20, 30, 40, 50])
print("Sliced (1:4):", arr[1:4])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Row 1, Col 0:2\n", arr2d[1, 0:2])

Sliced (1:4): [20 30 40]
Row 1, Col 0:2
 [4 5]


In [ ]:
# NumPy Data Types
arr = np.array([1, 2, 3], dtype='float32')
print("Array:", arr)
print("Data Type:", arr.dtype)

Array: [1. 2. 3.]
Data Type: float32


In [ ]:
# NumPy Copy vs View
# View (shared data)
arr = np.array([1, 2, 3])
view = arr.view()
view[0] = 100
print("Original (after view change):", arr)

# Copy (separate data)
copy = arr.copy()
copy[1] = 200
print("Original (after copy change):", arr)

Original (after view change): [100   2   3]
Original (after copy change): [100   2   3]


In [ ]:
# NumPy Array Shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Size: 6
Dimensions: 2


In [ ]:
# NumPy Array Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# NumPy Array Iterating
arr = np.array([[1, 2], [3, 4]])

# Iterate over rows
for row in arr:
    print("Row:", row)

# Iterate over each element
for x in np.nditer(arr):
    print("Element:", x)

Row: [1 2]
Row: [3 4]
Element: 1
Element: 2
Element: 3
Element: 4


In [19]:
# NumPy Array Join
# axis < dimensions

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined = np.concatenate((arr1, arr2))
print("Joined 1D:", joined)
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

joined_axis0 = np.concatenate((arr3, arr4), axis=0)
joined_axis1 = np.concatenate((arr3, arr4), axis=1)
print("Joined axis=0:\n", joined_axis0)
print("Joined axis=1:\n", joined_axis1)

Joined 1D: [1 2 3 4 5 6]
Joined axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joined axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [25]:
# NumPy Array Split
arr = np.array([10, 20, 30, 40, 50, 60])
split = np.array_split(arr, 3)
print("Split 1D:")
for s in split:
    print(s)

arr2d = np.array([[1, 2], [3, 4], [5, 6]])
split2d = np.array_split(arr2d, 2)
print("Split 2D:")
for s in split2d:
    print(s)

Split 1D:
[10 20]
[30 40]
[50 60]
Split 2D:
[[1 2]
 [3 4]]
[[5 6]]


In [36]:
# NumPy Array Search
arr = np.array([10,20,30,40,30])
index = np.where(arr == 30)
print(index)

(array([2, 4]),)


In [47]:
# NumPy Array Sort
arr = np.array([3, 1, 4, 2])
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

arr2d = np.array([[3, 2,-1], [1, 4,-2]])
print("Sorted rows:\n", np.sort(arr2d, axis=0)) # axis = 0 is used to sort column wise


Sorted array: [1 2 3 4]
Sorted rows:
 [[ 1  2 -2]
 [ 3  4 -1]]


In [49]:
# NumPy Array Filter
arr = np.array([10, 20, 30, 40])
filter_arr = arr > 25
print("Boolean filter:", filter_arr)

result = arr[filter_arr]
print("Filtered result (arr > 25):", result)


[ True False  True False False  True  True  True]
[18 20 23 25 30]
