<a href="https://colab.research.google.com/github/hossainsiam133/Machine-Learning/blob/main/NumPy/03_NumPy_Ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Intro
import numpy as np
a = [1,2,3]
b = [6,7,8]
c = []
for x,y in zip(a,b):
    c.append(x+y)
print(c)

z = np.add(a,b)
print(z)


[7, 9, 11]
[ 7  9 11]


In [ ]:
# Create your own ufunc for addition:
def AddFunc(a,b):
  return a+b
myAdd = np.frompyfunc(AddFunc,2,1)
print(myAdd([1,2,3],[6,7,8]))

[7 9 11]


In [ ]:
# Simple Arithmetic
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

# Addition
print("Addition:",np.add(arr1,arr2))
# Substraction
print("Subtraction:",np.subtract(arr1,arr2))
# Multiplication
print("Multiplication:",np.multiply(arr1,arr2))
# Division
print("Division:",np.divide(arr1,arr2))
# Power
print("Power:",np.power(arr1,arr2))
# Reminder
print("Reminder:",np.mod(arr1,arr2))
# Quotient and Mod
print("Quotient and Mod",np.divmod(arr1,arr2)) # integer division
# Absolute Values
print("Absolute Values",np.abs([-1,-0,3,-9,3,4]))


Addition: [13 25 36 48 52 93]
Subtraction: [ 7 15 24 32 48 27]
Multiplication: [  30  100  180  320  100 1980]
Division: [ 3.33333333  4.          5.          5.         25.          1.81818182]
Power: [         1000       3200000     729000000 6553600000000          2500
             0]
Reminder: [ 1  0  0  0  0 27]
Quotient and Mod (array([ 3,  4,  5,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))
Absolute Values [1 0 3 9 3 4]


In [ ]:
# There are primarily five ways of rounding off decimals in NumPy:
# truncation
# fix
# rounding
# floor
# ceil

# 1. truncation
arr = [-3.666,3.6667]
print("Truncation:",np.trunc(arr))

# 2. fix
print("Fix:",np.fix(arr))

# 3. rounding
# arr = np.around(3,1666,1)
# print("Round:",arr)

# 4. floor
print("Floor:",np.floor(3.1416))

# 5. Ceil
print("Ceil:",np.ceil(3.1416))

Truncation: [-3.  3.]
Fix: [-3.  3.]
Floor: 3.0
Ceil: 4.0


In [ ]:
# Log at Base 2
arr = np.arange(1,6)
print(arr)
print("Log at Base 2:",np.log2(arr))
print("Log at Base 10:",np.log10(arr))
print("Expontial:",np.log(arr))

[1 2 3 4 5]
Log at Base 2: [0.         1.         1.5849625  2.         2.32192809]
Log at Base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Expontial: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Ufunc Summation
arr1 = [1,2,3]
arr2 = [1,2,3]
print("Total Sum:",np.sum([arr1,arr2]))

# Summation Over an Axis
print("Sum on X Axis:",np.sum([arr1,arr2],axis=1))

# Cummulative Sum
print("Cummulative Sum:",np.cumsum([1,2,3,4,5]))

Total Sum: 12
Sum on X Axis: [6 6]
Cummulative Sum: [ 1  3  6 10 15]


In [ ]:
# Products
arr1 = np.array([1,2,3,4])
print("Products:",np.prod(arr1))

# Products 2D
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

# Products in Y axis
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
newarr = np.prod([arr1, arr2], axis=0)
print("Products in Y axis:",newarr)

# Cumalative Products
print("Cumalative Products",np.cumprod([1,2,3,4,5]))

Products: 24
40320
Products in Y axis: [ 5 12 21 32]
Cumalative Products [  1   2   6  24 120]


In [8]:
# Differences
arr = np.array([3,5,7,10,3])
print("Difference 1st time:",np.diff(arr))
print("Difference 2nd time:",np.diff(arr,n=2))

Difference 1st time: [ 2  2  3 -7]
Difference 2nd time: [  0   1 -10]


In [15]:
# LCM GCD
num1 = 4
num2 = 6
print("LCM",np.lcm(num1,num2))

arr = np.array([3,6,9])
print("LCM in Array:",np.lcm.reduce(arr))
print()
print("GCD:",np.gcd(num1,num2))
print("GCD in Array:",np.gcd.reduce(arr))

LCM 12
LCM in Array: 18

GCD: 2
GCD in Array: 3


In [38]:
# Trigonometric Functions
print(np.sin(np.pi/2))
arr = np.array([np.pi/2,np.pi/3,np.pi/6])
print(np.sin(arr))

# Convert Degrees Into Radians
arr = np.array([90,180,270,360])
print("Radians:",np.deg2rad(arr))

# Radians to Degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
print("Degrees:",np.rad2deg(arr))

# Finding Angles
print("Angle:",np.arcsin(1))

# Finding Angles in Arrray

arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print("Array Angles:",x)

# Pythagoras theorem
base = 4
perp = 6
print("hypotenuse:",np.hypot(base,perp))

1.0
[1.        0.8660254 0.5      ]
Radians: [1.57079633 3.14159265 4.71238898 6.28318531]
Degrees: [ 90. 180. 270. 360.]
Angle: 1.5707963267948966
Array Angles: [ 1.57079633 -1.57079633  0.10016742]
hypotenuse: 7.211102550927978


In [41]:
# Hyperbolic Functions
print(np.sinh(np.pi*0.5))

2.3012989023072947


In [57]:
# NumPy Set Operations
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
print("Unique Elements:",np.unique(arr))

# Finding Union
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,7,1,4])
print("Union:",np.union1d(arr1,arr2))

# Finding Intersection
# Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation.
# It should always be set to True when dealing with sets.
print("Intersect:",np.intersect1d(arr1,arr2,assume_unique=True))

# Finding Difference
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
print("Differnce:",np.setdiff1d(set1,set2)) # Those elements which is present in set1 but not in set2

# Finding Symmetric Difference
# To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
print("Symmetric Difference:",np.setxor1d(set1,set2))


Unique Elements: [1 2 3 4 5 6 7]
Union: [1 2 3 4 5 7]
Intersect: [1 1 4]
Differnce: [1 2]
Symmetric Difference: [1 2 5 6]
